### ISSUE TITLE
Location of Opencv library file

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#19]
I have come across a file 'CascadeClassifier' in opencv at OpenCVLibrary320/org.opencv/objdetect/CascadeClassifier.java where certain native functions appear red
<img width="611" alt="opencv_lib" src="https://cloud.githubusercontent.com/assets/10016848/26520025/513385aa-42e8-11e7-9198-222587be9b4d.PNG">

**Can I please know from which library are the opencv implementations of these functions present and where is the location of this library file in the project**

AS , when I try to run entire project from scratch, I get below error at runtime

 java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10__Ljava_lang_String_2)
                                                                                         at org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(Native Method)
                                                                                         at org.opencv.objdetect.CascadeClassifier.<init>(CascadeClassifier.java:39)
                                                                                         at com.example.h242018.facerecognition.Helpers.FaceDetection.setCascadeClassifier(FaceDetection.java:68)
                                                                                         at com.example.h242018.facerecognition.Helpers.FaceDetection.<init>(FaceDetection.java:52)
                                                                                         at com.example.h242018.facerecognition.PreProcessor.PreProcessorFactory.<init>(PreProcessorFactory.java:56)
                                                                                         at com.example.h242018.facerecognition.Activities.TrainingActivity$1.run(TrainingActivity.java:70)
                                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by sladomic** [comment]
@ashokbugude the native libs can be found here:

![image](https://cloud.githubusercontent.com/assets/556222/26520088/3c164340-42cc-11e7-8697-c830575b30e0.png)

OpenCV was included like this:

http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.html

But I just changed it a bit, so OpenCV is now included from here:

https://bintray.com/qualeams/Android-Face-Recognition-Deep-Learning-Library/OpenCV

If you really want to change the native source code of OpenCV, than probably this would help, but it seems to be a bit outdated, since it's still explained for Eclipse only:

http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/android_dev_intro.html

**Comment by ashokbugude** [comment]
Thanks very much, I am trying to eliminate Android.mk and Application.mk with cmakelists.txt ,hence facing these issues. Thanks once again

**Comment by ashokbugude** [comment]
I have added the opencv lib file to the project as shown below,
![image](https://cloud.githubusercontent.com/assets/10016848/26521410/91a29258-4305-11e7-9710-828d3c0835c1.png)


But still I face the same issues

05-27 17:01:01.153 18919-18919/com.example.h242018.facerecognition E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
05-27 17:01:01.293 18919-18919/com.example.h242018.facerecognition E/art: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10__Ljava_lang_String_2)
05-27 17:01:01.293 18919-18919/com.example.h242018.facerecognition E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.example.h242018.facerecognition, PID: 18919
                                                                                     java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10__Ljava_lang_String_2)
                                                                                         at org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(Native Method)
                                                                                         at org.opencv.objdetect.CascadeClassifier.<init>(CascadeClassifier.java:33)
                                                                                         at com.example.h242018.facerecognition.Helpers.FaceDetection.setCascadeClassifier(FaceDetection.java:68)
                                                                                         at com.example.h242018.facerecognition.Helpers.FaceDetection.<init>(FaceDetection.java:52)
                                                                                         at com.example.h242018.facerecognition.PreProcessor.PreProcessorFactory.<init>(PreProcessorFactory.java:56)
                                                                                         at com.example.h242018.facerecognition.Activities.DetectionActivity.onResume(DetectionActivity.java:104)
                                                                                         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1265)
                                                                                         at android.app.Activity.performResume(Activity.java:6384)
                                                                                         at android.app.Activity.performResume(Activity.java:6738)
                                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3170)
                                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3216)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2557)
                                                                                         at android.app.ActivityThread.access$1000(ActivityThread.java:166)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Can I know what could be the issue**, below is the content of my scmakelists.txt

cke_minimum_required(VERSION 3.4.1)


add_library( jnilibsvm SHARED src/main/cpp/svm/jnilibsvm.cpp
                              src/main/cpp/svm/common.cpp
                              src/main/cpp/svm/libsvm/svm-train.cpp
                              src/main/cpp/svm/libsvm/svm-predict.cpp
                              src/main/cpp/svm/libsvm/svm.cpp)

find_library( log-lib log )

add_library( opencv_java3 STATIC IMPORTED )
set_target_properties( opencv_java3 PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/libs/libopencv_java3.so )

target_link_libraries(jnilibsvm opencv_java3 ${log-lib})

I have added
 static {
        System.loadLibrary("opencv_java3");
    }
in ' CascadeClassifier.java' , but still get 
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.h242018.facerecognition-2/base.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.h242018.facerecognition-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.h242018.facerecognition-2/lib/arm, /data/app/com.example.h242018.facerecognition-2/base.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_dependencies_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_0_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_1_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_2_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_3_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_4_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_5_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_6_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_7_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_8_apk.apk!/lib/armeabi, /data/app/com.example.h242018.facerecognition-2/split_lib_slice_9_apk.apk!/lib/armeabi, /vendor/lib, /system/lib]]] couldn't find "libopencv_java3.so" error

**Comment by sladomic** [comment]
Somehow the opencv_java3 library seems to be empty. In the end you need to have some native libs and tell build.gradle where to find them if they are not stored at the usual location https://developer.android.com/studio/projects/add-native-code.html#link-gradle

**Comment by ashokbugude** [comment]
Thanks It got resolved
