### ISSUE TITLE
How to change the default settings?

### ISSUE THREAD

**Issue by dyt001** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#35]
I am now trying to run this on Android. I can not find the file to change the default settings when I change the model. Can anyone kindly tell me? Thanks!

**Comment by sladomic** [comment]
It is not really intuitive since the library and the test framework were first just one app. The default settings can be set in the library https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/blob/master/facerecognitionlibrary/src/main/res/xml/preferences.xml or alternatively you could set/overwrite them programmatically

**Comment by dyt001** [comment]
Thanks! So if I want to change a model, I need to change the settings and model paths in the library, right?

**Comment by sladomic** [comment]
Can you quickly elaborate your use case?

**Comment by dyt001** [comment]
I am now running the example with Android Studio. I copy the three model to "/sdcard/Pictures/facerecognition/data/TensorFlow" and  "/sdcard/Pictures/facerecognition/data/caffe". But it can't useon the phone. I don't know if it is because the model paths or settings is wrong. The logcat shows below:
02-20 16:20:47.657 14816-14816/? I/art: Late-enabling -Xcheck:jni
02-20 16:20:47.767 14816-14816/ch.zhaw.facerecognition I/HwCust: Constructor found for class android.app.HwCustApplicationPackageManagerImpl
02-20 16:20:48.117 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x32 a=-1}
02-20 16:20:48.117 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x32 a=-1}
02-20 16:20:48.117 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.117 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x140 a=-1}
02-20 16:20:48.127 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.127 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0xf0 a=-1}
02-20 16:20:48.127 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.127 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x14 a=-1}
02-20 16:20:48.127 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.127 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x1f4 a=-1}
02-20 16:20:48.137 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.137 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0xa0 a=-1}
02-20 16:20:48.137 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.137 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x4/d=0x3f8ccccd a=-1}
02-20 16:20:48.137 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x4/d=0x3f8ccccd a=-1}
02-20 16:20:48.137 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.147 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x3 a=-1}
02-20 16:20:48.147 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.147 14816-14816/ch.zhaw.facerecognition W/Resources: Converting to string: TypedValue{t=0x10/d=0x2 a=-1}
02-20 16:20:48.147 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.157 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.157 14816-14816/ch.zhaw.facerecognition E/textview: initAddtionalStyle default
02-20 16:20:48.157 14816-14816/ch.zhaw.facerecognition E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: ch.zhaw.facerecognition, PID: 14816
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.zhaw.facerecognition/ch.zhaw.facerecognition.Activities.MainActivity}: android.view.InflateException: Binary XML file line #179: Error inflating class java.lang.reflect.Constructor
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                             at android.app.ActivityThread.access$1200(ActivityThread.java:152)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5538)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
                                                                          Caused by: android.view.InflateException: Binary XML file line #179: Error inflating class java.lang.reflect.Constructor
                                                                             at android.preference.GenericInflater.createItem(GenericInflater.java:397)
                                                                             at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:326)
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:263)
                                                                             at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:485)
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:444)
                                                                             at ch.zhaw.facerecognition.Activities.MainActivity.onCreate(MainActivity.java:54)
                                                                             at android.app.Activity.performCreate(Activity.java:6013)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5538) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                             at android.preference.GenericInflater.createItem(GenericInflater.java:383)
                                                                             at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430) 
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:481) 
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:493) 
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:326) 
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:263) 
                                                                             at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272) 
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:485) 
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:444) 
                                                                             at ch.zhaw.facerecognition.Activities.MainActivity.onCreate(MainActivity.java:54) 
                                                                             at android.app.Activity.performCreate(Activity.java:6013) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5538) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753) 
                                                                          Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                             at android.preference.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:222)
                                                                             at android.preference.Preference.<init>(Preference.java:271)
                                                                             at android.preference.DialogPreference.<init>(DialogPreference.java:70)
                                                                             at android.preference.MultiSelectListPreference.<init>(MultiSelectListPreference.java:50)
                                                                             at android.preference.MultiSelectListPreference.<init>(MultiSelectListPreference.java:61)
                                                                             at android.preference.MultiSelectListPreference.<init>(MultiSelectListPreference.java:65)
                                                                             at ch.zhaw.facerecognition.Helpers.MultiSelectListPreference.<init>(MultiSelectListPreference.java:23)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                             at android.preference.GenericInflater.createItem(GenericInflater.java:383) 
                                                                             at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430) 
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:481) 
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:493) 
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:326) 
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:263) 
                                                                             at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272) 
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:485) 
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:444) 
                                                                             at ch.zhaw.facerecognition.Activities.MainActivity.onCreate(MainActivity.java:54) 
                                                                             at android.app.Activity.performCreate(Activity.java:6013) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5538) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753) 
02-20 16:20:48.477 14816-14816/ch.zhaw.facerecognition I/Process: Sending signal. PID: 14816 SIG: 9

**Comment by dyt001** [comment]
And I am trying to change a new model to do the face Recognition. But I can not find how to change it in the test example.

**Comment by sladomic** [comment]
The path looks correct but in the settings you should just use the model name (e.g. "model.pb"). Is that what you tried?

**Comment by dyt001** [comment]
Because I don't know which model the example used. I downloaded the three model you mentioned to the paths. The model name I used is "tensorflow_inception_graph.pb", "vgg_faces.pb" and "VGG_FACE.caffemodel","VGG_FACE_deploy.prototxt". And I can't find the file which writes the model paths and name in the "Android-Face-Recognition-with-Deep-Learning-Test-Framework/app/src/main/java/ch/zhaw/facerecognition/Activities/"

**Comment by sladomic** [comment]
Ok, sorry. So the user manual was written with the original app, which used one of 3 models. Since then there have been some changes. The current app already includes a model "optimized_facenet.pb" which is better and faster than any of the old models (https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/blob/master/facerecognitionlibrary/src/main/assets/optimized_facenet.pb). Here you can see, how the Tensorflow interface is initialized with the model name derived from the preferences https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/blob/dbe92113b180798571383edd377f9ab0f9b5d099/facerecognitionlibrary/src/main/java/ch/zhaw/facerecognitionlibrary/Recognition/TensorFlow.java#L75

**Comment by dyt001** [comment]
Thanks！I think this is why I can not use it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
