### ISSUE TITLE
How can it run on the x86 CPU

### ISSUE THREAD

**Issue by gluttonyOwO** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#44]
I have the device x86 CPU. 
And here is my Error,that I have.
and How can I do to fix it?

E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper: Library list: ""
                       First attempt to load libs
                       Trying to init OpenCV libs
D/OpenCV/StaticHelper: Trying to load library opencv_java3
D/OpenCV/StaticHelper: Cannot load library "opencv_java3"
W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ch.zhaw.facerecognition-nZXJudycSK0TBpgCx4Pegw==/base.apk"],nativeLibraryDirectories=[/data/app/ch.zhaw.facerecognition-nZXJudycSK0TBpgCx4Pegw==/lib/x86, /system/fake-libs, /data/app/ch.zhaw.facerecognition-nZXJudycSK0TBpgCx4Pegw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libopencv_java3.so"
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                  at java.lang.System.loadLibrary(System.java:1657)
                  at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
                  at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
                  at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
                  at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:91)
W/System.err:     at ch.zhaw.facerecognition.Activities.AddPersonPreviewActivity.<clinit>(AddPersonPreviewActivity.java:66)
                  at java.lang.Class.newInstance(Native Method)
                  at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                  at android.os.Handler.dispatchMessage(Handler.java:106)
                  at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
D/OpenCV/StaticHelper: First attempt to load libs fails
D/CameraBridge: Attr count: 6
E/zygote: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10__Ljava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ch.zhaw.facerecognition, PID: 4140
                  java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_10__Ljava_lang_String_2)
                      at org.opencv.objdetect.CascadeClassifier.CascadeClassifier_0(Native Method)
                      at org.opencv.objdetect.CascadeClassifier.<init>(CascadeClassifier.java:31)
                      at ch.zhaw.facerecognitionlibrary.Helpers.FaceDetection.setCascadeClassifier(FaceDetection.java:68)
                      at ch.zhaw.facerecognitionlibrary.Helpers.FaceDetection.<init>(FaceDetection.java:52)
                      at ch.zhaw.facerecognitionlibrary.PreProcessor.PreProcessorFactory.<init>(PreProcessorFactory.java:56)
                      at ch.zhaw.facerecognition.Activities.AddPersonPreviewActivity.onResume(AddPersonPreviewActivity.java:207)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
                      at android.app.Activity.performResume(Activity.java:7117)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by sladomic** [comment]
The library is compiled for arm devices only. For x86 you would need to compile all the native libs and find the correct configs/instructions which I don't know.
